dist: xenial
language: go
sudo: true

go:
  - "tip"
  - "1.12.x"
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y clang llvm

script:
  # Verify for formatting issues
  - if [ -n "$(gofmt -s -l .)" ]; then echo "Please fix source formatting by 'go fmt ./...'"; false; fi
  # Run unit tests
  - go test -v -coverprofile=coverage.txt -covermode=atomic
  - cd goebpf_mock && go test -v -coverprofile=coverage.txt -covermode=atomic
  # Travis does not support operations with eBPF, so, just ensure that
  # integration test is compilable Run integration test
  - cd ../itest && make

after_success:
  - bash <(curl -s https://codecov.io/bash)
