// @generated by bpf_enum_gen. DO NOT EDIT.
// Source: /usr/include/linux/bpf.h

package goebpf

// ProgramType is generated from enum bpf_prog_type in /usr/include/linux/bpf.h
type ProgramType int

const (
	ProgramTypeUnspec ProgramType = iota
	ProgramTypeSocketFilter
	ProgramTypeKprobe
	ProgramTypeSchedCls
	ProgramTypeSchedAct
	ProgramTypeTracepoint
	ProgramTypeXdp
	ProgramTypePerfEvent
	ProgramTypeCgroupSkb
	ProgramTypeCgroupSock
	ProgramTypeLwtIn
	ProgramTypeLwtOut
	ProgramTypeLwtXmit
	ProgramTypeSockOps
	ProgramTypeSkSkb
	ProgramTypeCgroupDevice
	ProgramTypeSkMsg
	ProgramTypeRawTracepoint
	ProgramTypeCgroupSockAddr
	ProgramTypeLwtSeg6local
	ProgramTypeLircMode2
	ProgramTypeSkReuseport
	ProgramTypeFlowDissector
	ProgramTypeCgroupSysctl
	ProgramTypeRawTracepointWritable
	ProgramTypeCgroupSockopt
	ProgramTypeTracing
	ProgramTypeStructOps
	ProgramTypeExt
	ProgramTypeLsm
	ProgramTypeSkLookup
	ProgramTypeSyscall
	ProgramTypeNetfilter
	maxBpfProgramType
)
